// Central constants for Provider Management (ADM-020 & ADM-021)
import {
  Sparkles,
  Dumbbell,
  Activity,
  Heart,
  Flower2,
  Hotel,
  ShieldCheck,
  BadgeAlert,
  Clock,
  UserCheck,
  FileCheck,
  AlertTriangle,
  CreditCard,
  Ban,
  CheckCircle2,
} from 'lucide-react'

export const PROVIDER_TYPES = [
  {
    id: 'massage_therapist',
    label: 'Massage Therapists',
    singular: 'Massage Therapist',
    category: 'individual',
    icon: Sparkles,
    color: '#7c3aed',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    accent: '#5c2dd5',
  },
  {
    id: 'fitness_trainer',
    label: 'Personal Trainers',
    singular: 'Personal Trainer',
    category: 'individual',
    icon: Dumbbell,
    color: '#6366f1',
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    accent: '#4f46e5',
  },
  {
    id: 'physiotherapy',
    label: 'Physiotherapy & Recovery',
    singular: 'Physiotherapist',
    category: 'individual',
    icon: Activity,
    color: '#8b5cf6',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    accent: '#7c3aed',
  },
  {
    id: 'yoga_specialist',
    label: 'Yoga Specialists',
    singular: 'Yoga Specialist',
    category: 'individual',
    icon: Heart,
    color: '#9333ea',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    accent: '#9333ea',
  },
  {
    id: 'meditation_specialist',
    label: 'Meditation Specialists',
    singular: 'Meditation Specialist',
    category: 'individual',
    icon: Sparkles,
    color: '#10b981',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    accent: '#059669',
  },
  {
    id: 'spa',
    label: 'Spas & Wellness Centers',
    singular: 'Spa & Wellness Center',
    category: 'business',
    icon: Flower2,
    color: '#3b82f6',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    accent: '#2563eb',
  },
  {
    id: 'hotel_resort',
    label: 'Hotels & Wellness Resorts',
    singular: 'Hotel & Wellness Resort',
    category: 'business',
    icon: Hotel,
    color: '#475569',
    bg: 'bg-slate-50',
    border: 'border-slate-200',
    accent: '#334155',
  },
]

export const PROVIDER_STATUSES = {
  active: {
    id: 'active',
    label: 'Active',
    color: '#16a34a',
    dotColor: 'bg-emerald-500',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    icon: CheckCircle2,
  },
  pending: {
    id: 'pending',
    label: 'Pending Verification',
    color: '#f59e0b',
    dotColor: 'bg-amber-500',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    icon: Clock,
  },
  under_review: {
    id: 'under_review',
    label: 'Under Review',
    color: '#8b5cf6',
    dotColor: 'bg-purple-500',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    icon: UserCheck,
  },
  suspended: {
    id: 'suspended',
    label: 'Suspended',
    color: '#ef4444',
    dotColor: 'bg-rose-500',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    icon: Ban,
  },
  inactive: {
    id: 'inactive',
    label: 'Inactive',
    color: '#94a3b8',
    dotColor: 'bg-slate-400',
    badgeClass: 'bg-slate-100 text-slate-600 border-slate-200',
    icon: Clock,
  },
}

export const VERIFICATION_STAGES = [
  { id: 'submitted', label: 'Submitted', key: 'submitted' },
  { id: 'awaiting_review', label: 'Awaiting Review', key: 'awaitingReview' },
  { id: 'approved', label: 'Approved', key: 'approved' },
  { id: 'rejected', label: 'Rejected / Changes Required', key: 'rejected' },
]

export const CONTENT_APPROVAL_TYPES = [
  { id: 'profile_photos', label: 'Profile Photos', icon: 'image' },
  { id: 'gallery_photos', label: 'Gallery Photos', icon: 'images' },
  { id: 'profile_info', label: 'Profile Information', icon: 'user' },
  { id: 'services_descriptions', label: 'Services / Descriptions', icon: 'list' },
  { id: 'business_info', label: 'Business Information', icon: 'building' },
]

export const PROVIDER_QUALITY_KEYS = [
  { id: 'rating_4_5_plus', label: '4.5+ Rating', icon: 'star', color: '#eab308' },
  { id: 'high_completion', label: 'High Completion Rate', icon: 'check', color: '#16a34a' },
  { id: 'low_cancellation', label: 'Low Cancellation', icon: 'shield', color: '#8b5cf6' },
  { id: 'needs_review', label: 'Needs Performance Review', icon: 'alert', color: '#ef4444' },
]

